version: "3"
volumes:
  postgres16.2-postgis3.4:
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres16.2-postgis3.4
    container_name: postgres16.2-postgis3.4
    volumes:
      - postgres16.2-postgis3.4:/var/lib/postgresql/data
      - ./backups:/opt/backups
    environment:
      # Postgres administrator password
      - POSTGRES_PASSWORD=adminpassword
      # Read-only login
      - READ_LOGIN=reader
      - READ_PASSWORD=readerpassword
      # https://pgtune.leopard.in.ua/
      # DB Version: 15
      # OS Type: linux
      # DB Type: web
      # Total Memory (RAM): 4 GB
      # CPUs num: 2
      # Connections num: 75
      # Data Storage: ssd
      - MAX_CONNECTIONS=75
      - SHARED_BUFFERS=1GB
      - EFFECTIVE_CACHE_SIZE=3GB
      - MAINTENANCE_WORK_MEM=256MB
      - CHECKPOINT_COMPLETION_TARGET=0.9
      - WAL_BUFFERS=16MB
      - DEFAULT_STATISTICS_TARGET=100
      - RANDOM_PAGE_COST=1.1
      - EFFECTIVE_IO_CONCURRENCY=200
      - WORK_MEM=6990kB
      - MIN_WAL_SIZE=1GB
      - MAX_WAL_SIZE=4GB
    networks:
    - postgres_conn
    ports:
    - "5432:5432"

networks:
  postgres_conn:
    driver: bridge
